language: java
services:
  - docker
jdk:
  - oraclejdk8
before_install:
  - docker -v
  - docker-compose -v
before_script:
  - docker-compose up --build -d
script:
  - mvn test -Ptest-ITBusiness -B
after_script:
  - docker-compose down